// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiLUDst76pJPILaHkX0QuEYJzzQRCfTUo',
    appId: '1:197135685598:web:d5e9169792eb8bc7b4ef4f',
    messagingSenderId: '197135685598',
    projectId: 'scholar-chat-4d484',
    authDomain: 'scholar-chat-4d484.firebaseapp.com',
    storageBucket: 'scholar-chat-4d484.appspot.com',
    measurementId: 'G-EW4175ZNRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoRDMDlaPFb5mkzZtiHqw73Jzfv-nfavY',
    appId: '1:197135685598:android:71ea39525856c9d9b4ef4f',
    messagingSenderId: '197135685598',
    projectId: 'scholar-chat-4d484',
    storageBucket: 'scholar-chat-4d484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4pEcA69LZnEv81NZsVp7GI8mUdJYVpvE',
    appId: '1:197135685598:ios:cc7ae93e9671ea4db4ef4f',
    messagingSenderId: '197135685598',
    projectId: 'scholar-chat-4d484',
    storageBucket: 'scholar-chat-4d484.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxv_D2wcwcPryrtMDNZ9Ruh17TwJGyy4',
    appId: '1:956199470017:ios:332ce9ef083cbb8e0ca540',
    messagingSenderId: '956199470017',
    projectId: 'quixotic-galaxy-420619',
    storageBucket: 'quixotic-galaxy-420619.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC4pb3ck7zkK87PKvzT1I-TBSC1qRDymc',
    appId: '1:956199470017:web:fc0451cbcf52c7f60ca540',
    messagingSenderId: '956199470017',
    projectId: 'quixotic-galaxy-420619',
    authDomain: 'quixotic-galaxy-420619.firebaseapp.com',
    storageBucket: 'quixotic-galaxy-420619.appspot.com',
    measurementId: 'G-JV2RH63H7D',
  );

}